In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pickle

In [ ]:


X_train_filename = '/content/drive/MyDrive/IE434 Deep Dive 11 project/Deep Dive 3 (Milestone 2)/X_train.pkl'

with open(X_train_filename, 'rb') as file:
    X_train = pickle.load(file)

X_test_filename = '/content/drive/MyDrive/IE434 Deep Dive 11 project/Deep Dive 3 (Milestone 2)/X_test.pkl'

with open(X_test_filename, 'rb') as file:
    X_test = pickle.load(file)


y_train_filename = '/content/drive/MyDrive/IE434 Deep Dive 11 project/Deep Dive 3 (Milestone 2)/y_train.pkl'

with open(y_train_filename, 'rb') as file:
    y_train = pickle.load(file)


y_test_filename = '/content/drive/MyDrive/IE434 Deep Dive 11 project/Deep Dive 3 (Milestone 2)/y_test.pkl'

with open(y_test_filename, 'rb') as file:
    y_test = pickle.load(file)

In [ ]:
#Amarthya's path

X_test_filename = '/content/drive/MyDrive/IE434 Deep Dive 11 project/Deep Dive 4 (Milestone 3)/X_test.pkl'

with open(X_test_filename, 'rb') as file:
    X_test = pickle.load(file)


y_test_filename = '/content/drive/MyDrive/IE434 Deep Dive 11 project/Deep Dive 4 (Milestone 3)/y_test.pkl'

with open(y_test_filename, 'rb') as file:
    y_test = pickle.load(file)

y_test_df = '/content/drive/MyDrive/IE434 Deep Dive 11 project/Deep Dive 4 (Milestone 3)/y_test_numerical.pkl'

with open(y_test_df, 'rb') as file:
    y_test_df = pickle.load(file)

In [ ]:
X_train.columns

Index(['start_lat', 'start_lng', 'PRCP', 'SNOW', 'TMAX', 'TMIN',
       'day_of_week_Monday', 'day_of_week_Saturday', 'day_of_week_Sunday',
       'day_of_week_Thursday', 'day_of_week_Tuesday', 'day_of_week_Wednesday',
       'month_August', 'month_December', 'month_February', 'month_January',
       'month_July', 'month_June', 'month_March', 'month_May',
       'month_November', 'month_October', 'month_September'],
      dtype='object')

Building a logistic regression model as our baseline learning model.

In [ ]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

# Assuming X_train, X_test, Y_train, and Y_test are already defined and available

# Create a logistic regression model
model = LogisticRegression(multi_class='multinomial', solver='lbfgs')

# Train the model
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)


# Generate and print confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print('Confusion Matrix:')
print(conf_matrix)

Accuracy: 0.0
Confusion Matrix:
[[ 785   35 1433]
 [  55  882 1190]
 [ 445  431 3888]]


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
import numpy as np

accuracy = np.trace(conf_matrix) / np.sum(conf_matrix)
print("Accuracy:", accuracy)

Accuracy: 0.6075021872265967
